---
- name: Configure Splunk Indexer
  hosts: indexer_server
  become: yes

  vars:
    splunk_home_path: "/opt/splunk"
    splunk_user: "splunk"
    splunk_group: "splunk"
    splunk_config_path: "/opt/splunk/etc/apps/lab/local"

  tasks:
    - name: Create inputs.conf file
      ansible.builtin.copy:
        dest: "{{ splunk_config_path }}/inputs.conf"
        content: |
          [splunktcp://9997]
          queueSize = 2MB
          disabled = false

    - name: Create output.conf file
      ansible.builtin.copy:
        dest: "{{ splunk_config_path }}/output.conf"
        content: |
          [tcpout]
          disabled = true

    - name: Create indexes.conf file
      ansible.builtin.copy:
        dest: "{{ splunk_config_path }}/indexes.conf"
        content: |
          [linux]
          coldPath = $SPLUNK_DB/linux/colddb
          enableDataIntegrityControl = 0
          enableTsidxReduction = 0
          homePath = $SPLUNK_DB/linux/db
          maxTotalDataSizeMB = 512000
          thawedPath = $SPLUNK_DB/linux/thaweddb

    - name: Set Splunk ownership
      ansible.builtin.file:
        path: "{{ splunk_home_path }}"
        owner: "{{ splunk_user }}"
        group: "{{ splunk_group }}"
        recurse: yes

    - name: Restart Splunk
      command: "{{ splunk_home_path }}/bin/splunk restart"
      become: true
      become_method: sudo
